### ISSUE TITLE
Tablet style fixes

### ISSUE THREAD

**Issue by dkastl** [consento-org/consento-website#13] opened 2020-02-01 15:02 UTC
See the comments in the screnshot

![capture_ipad](https://user-images.githubusercontent.com/227762/73594186-3a3c8880-454f-11ea-93ee-0e848697f333.png)

**Comment by marcchataigner-zz** [comment] 2020-02-03 01:35
@Torgian would it be possible to add background colours for sections? 

Like: 

![Screen Shot 2020-02-03 at 10 35 31](https://user-images.githubusercontent.com/3974900/73619483-ec1fa600-4670-11ea-9113-9d2a84317ea6.png)

**Comment by Torgian** [comment] 2020-02-03 01:58
Background colors could work, but the problem is that some of the images need to be converted to pngs that do not show a white background. Unfortunately, whenever I optimize the images for size, the transparent background is removed and replaced with a white background. 

I am thinking of just using horizontal breaks instead.

**Comment by Torgian** [comment] 2020-02-03 07:24
Majority of this is fixed.

**Comment by Torgian** [comment] 2020-02-04 15:56
I've done quite a lot of changes tonight, so please double check.

**Comment by Torgian** [comment] 2020-02-04 16:08
For tablet mode, look into the sections with 4 icons and 5 icons. Make the 4 icons into a 2x2 section, and the 5 icons into either a 2x2x1, or a 2x1x2 section.

**Comment by Torgian** [comment] 2020-02-04 16:11
Also look into centering certain elements to look cleaner in tablet mode. Up to 768px should be ok. Don't forget to double check landscape mode.

**Comment by Torgian** [comment] 2020-02-04 22:22
In landscape mode, hamburger menu shows navigation items floating right. Needs to be centered.

**Comment by Torgian** [comment] 2020-02-04 23:57
Tablet mode: How it works and Our Values have changed. How it works is now 2x2 on anything other than large screens. Our Values is now 2x2x1, with the bottom element centered. 

Other issues fixed.

**Comment by Torgian** [comment] 2020-02-05 00:04
I think tablet mode still needs a couple of elements centered to look better. Some images get too small in tablet mode, so I will center these to look more like it does in mobile.

**Comment by martinheidegger** [comment] 2020-02-13 01:38
To close this issue, please open new issues with workable items.

**Closed as completed** 2020-02-26 11:38 UTC
